export const VERIFICATION_METHODS = Object.freeze({
  PROFILE_CODE: "PROFILE_CODE",
  GAME: "GAME",
});

export const VERIFICATION_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
});

export const VERIFICATION_SESSION_MS = 5 * 60 * 1000;
export const VERIFICATION_COLOR = 0x5865f2;
